### ISSUE TITLE
Add shared as npm dependency not working [Yarn workspace Issue]

### ISSUE THREAD

**Issue by ild-dsv** [codedailyio/yarn-workspaces-web-native#1]
Follow your instruction in video, I see that you add 'shared@1.0.0' as a npm dependency for web and native to share code from shared folder to web and native.
However when I try to use this command:
**yarn workspace web add shared@1.0.0**
or
**yarn workspace native add shared@1.0.0**

I got the issue:
Couldn't find any versions for "shared" that matches "1.0.0"
? Please choose a version of "shared" from this list:
❯ 0.2.0

Somethings like there already has a npm packages called 'shared', but it's not what we want, right?

How could I solve this problem?

Thanks in advance.

**Comment by ild-dsv** [comment]
I think it caused by my fault. Just missing local packages.json for shared folder.
Now it worked perfectly. Thanks for the awesome tutorial.

**Comment by browniefed** [comment]
Great! Glad it worked for you.
